### ISSUE TITLE
Wrap Formik FieldArray for arrays of objects

### ISSUE THREAD

**Issue by danielgtaylor** [istreamlabs/pebble-formik#16]
When configuring complex objects, it is useful to be able to add/remove objects inside of arrays. Formik has a specific component to help with this, called [`FieldArray`](https://formik.org/docs/api/fieldarray):

> `<FieldArray />` is a component that helps with common array/list manipulations. You pass it a name property with the path to the key within values that holds the relevant array. `<FieldArray />` will then give you access to array helper methods via render props.

Specifically, it gives you `arrayHelpers.insert(...)` and `arrayHelpers.remove(index)` functions that handle managing the data for you.

#### Use Case

My current use case, for example: a channel has multiple video encodings for different dimensions/bitrates. A user should be able to add/remove those as they see fit when creating or updating a channel. The data looks something like:

```js
{
  "vencoders": [
    {
      "id": "enc1",
      "width": 1920,
      "height": 1080,
      "bitrate": 123456,
    },
    // ...
  ]
}
```

I can use a state variable to track how many encodings there are and render them in a loop, but once an encoding has been added, the data remains in the Formik `values` (used by `validate` and `onSubmit`) even after I remove the fields from the rendered page output. I just can't get low-level access to the internals to remove them. It seems like using the built-in Formik component specifically for this use-case is the right way to go about this.

**Comment by esjaastad-isp** [comment]
This is solved by using 
```
import { useFormikContext } from 'formik';
const { values } = useFormikContext();
```
